rm *.txt
rm TRANS/*.txt
rm TRANS/0/*.txt
rm TRANS/1/*.txt
rm TRANS/TEST/*.txt
rm T/*.txt
rm T/0/*.txt
rm T/1/*.txt
rm S/*.txt
rm S/0/*.txt
rm S/1/*.txt
rm S/2/*.txt
rm S/3/*.txt
rm S/4/*.txt
rm S/5/*.txt
rm S/6/*.txt
rm S/7/*.txt
rm ST/0/*.txt
rm ST/0/0/*.txt
rm ST/0/1/*.txt
rm ST/0/TEST/*.txt
rm ST/1/0/*.txt
rm ST/1/1/*.txt
rm ST/1/TEST/*.txt
rm ST/2/0/*.txt
rm ST/2/1/*.txt
rm ST/2/TEST/*.txt
rm ST/3/0/*.txt
rm ST/3/1/*.txt
rm ST/3/TEST/*.txt
rm ST/4/0/*.txt
rm ST/4/1/*.txt
rm ST/4/TEST/*.txt
rm ST/5/0/*.txt
rm ST/5/1/*.txt
rm ST/5/TEST/*.txt
rm ST/6/0/*.txt
rm ST/6/1/*.txt
rm ST/6/TEST/*.txt
rm ST/7/0/*.txt
rm ST/7/1/*.txt
rm ST/7/TEST/*.txt
